export const agentProcedureCopy = {
  "ru-RU": {
    title: "Предложения по поиску данных",
    observations: "завершённых диалогов",
    apply: "Применить порядок",
    active: "Используется",
    rollback: "Вернуть исходное поведение",
    help: "Сохраняется порядок обращений к данным без клиентской информации. Для рассмотрения нужны хотя бы три завершённых диалога; это не оценка качества. Версию выбирает администратор, предыдущие решения сохраняются.",
    sources: {
      knowledge: "База знаний",
      organization: "Настройки центра",
      family: "Семья",
      schedule: "Расписание",
      center_analytics: "Аналитика центра",
      site_analytics: "Аналитика сайта",
      tracking_links: "Источники заявок",
    },
  },
  "en-US": {
    title: "Suggested lookup orders",
    observations: "completed conversations",
    apply: "Apply this order",
    active: "Active",
    rollback: "Restore base behavior",
    help: "Lookup order is retained without customer information. Review requires at least three completed conversations; this is not a quality score. An administrator selects the version, and previous decisions are retained.",
    sources: {
      knowledge: "Knowledge base",
      organization: "Center settings",
      family: "Family",
      schedule: "Schedule",
      center_analytics: "Center analytics",
      site_analytics: "Website analytics",
      tracking_links: "Acquisition sources",
    },
  },
  "pt-BR": {
    title: "Sugestões de ordem de consulta",
    observations: "conversas concluídas",
    apply: "Aplicar esta ordem",
    active: "Ativa",
    rollback: "Restaurar comportamento inicial",
    help: "A ordem de consulta é guardada sem informações dos clientes. A revisão exige três conversas concluídas; não é uma nota de qualidade. Um administrador seleciona a versão e as decisões anteriores são preservadas.",
    sources: {
      knowledge: "Base de conhecimento",
      organization: "Configurações do centro",
      family: "Família",
      schedule: "Horários",
      center_analytics: "Análises do centro",
      site_analytics: "Análises do site",
      tracking_links: "Origens dos contatos",
    },
  },
  "tr-TR": {
    title: "Önerilen sorgulama sıraları",
    observations: "tamamlanan görüşme",
    apply: "Bu sırayı uygula",
    active: "Etkin",
    rollback: "İlk davranışı geri yükle",
    help: "Sorgulama sırası müşteri bilgisi olmadan saklanır. İnceleme için en az üç tamamlanan görüşme gerekir; bu bir kalite puanı değildir. Sürümü yönetici seçer ve önceki kararlar korunur.",
    sources: {
      knowledge: "Bilgi tabanı",
      organization: "Merkez ayarları",
      family: "Aile",
      schedule: "Ders programı",
      center_analytics: "Merkez analizi",
      site_analytics: "Site analizi",
      tracking_links: "Başvuru kaynakları",
    },
  },
};
