export const agentCommunicationCopy = {
  "ru-RU": {
    title: "Общение с агентом",
    who: "Кто может обращаться",
    where: "Где отвечать",
    legacy: "Прежние ограничения — ещё не настроено",
    staff: "Все сотрудники центра",
    owner: "Только владелец",
    selected: "Выбранные сотрудники",
    both: "В каналах и личных сообщениях",
    channels: "Только в каналах",
    direct_messages: "Только в личных сообщениях",
    help: "В личке можно писать без @. В других каналах обращайтесь через @агента; Welcome сохраняет диалог без упоминаний. Агент должен быть участником переписки. Эти настройки не открывают данные центра внешним клиентам.",
    loading: "Загружаем сотрудников…",
    unavailable: "Список сотрудников недоступен. Сохранённый выбор не изменён.",
    retry: "Повторить",
    empty: "Выберите хотя бы одного сотрудника.",
    missing: "Сотрудник недоступен",
    search: "Найти сотрудника",
  },
  "en-US": {
    title: "Agent conversations",
    who: "Who can talk to this agent",
    where: "Where to reply",
    legacy: "Legacy restrictions — not configured",
    staff: "All center staff",
    owner: "Owner only",
    selected: "Selected staff",
    both: "Channels and direct messages",
    channels: "Channels only",
    direct_messages: "Direct messages only",
    help: "No @ is needed in DMs. Mention the agent in other channels; Welcome keeps its unmentioned conversation flow. The agent must be a conversation member. These settings do not expose internal center data to external clients.",
    loading: "Loading staff…",
    unavailable: "Staff list unavailable. Saved selections are unchanged.",
    retry: "Retry",
    empty: "Select at least one staff member.",
    missing: "Staff member unavailable",
    search: "Find staff",
  },
  "pt-BR": {
    title: "Conversas com o agente",
    who: "Quem pode conversar",
    where: "Onde responder",
    legacy: "Restrições anteriores — não configurado",
    staff: "Toda a equipe do centro",
    owner: "Somente proprietário",
    selected: "Pessoas selecionadas",
    both: "Canais e mensagens diretas",
    channels: "Somente canais",
    direct_messages: "Somente mensagens diretas",
    help: "Não é preciso @ nas mensagens diretas. Nos outros canais, mencione o agente; o Welcome mantém a conversa sem menções. O agente deve participar da conversa. Estas configurações não expõem dados internos a clientes externos.",
    loading: "Carregando equipe…",
    unavailable: "Lista indisponível. A seleção salva não mudou.",
    retry: "Tentar novamente",
    empty: "Selecione pelo menos uma pessoa.",
    missing: "Pessoa indisponível",
    search: "Buscar pessoa",
  },
  "tr-TR": {
    title: "Temsilciyle görüşme",
    who: "Kimler konuşabilir",
    where: "Nerede yanıt versin",
    legacy: "Önceki kısıtlamalar — yapılandırılmadı",
    staff: "Tüm merkez çalışanları",
    owner: "Yalnızca sahibi",
    selected: "Seçili çalışanlar",
    both: "Kanallar ve özel mesajlar",
    channels: "Yalnızca kanallar",
    direct_messages: "Yalnızca özel mesajlar",
    help: "Özel mesajlarda @ gerekmez. Diğer kanallarda temsilciyi etiketleyin; Welcome etiketsiz konuşmaya devam eder. Temsilci görüşmenin üyesi olmalıdır. Bu ayarlar merkez verilerini dış müşterilere açmaz.",
    loading: "Çalışanlar yükleniyor…",
    unavailable: "Çalışan listesi alınamadı. Kayıtlı seçim değişmedi.",
    retry: "Tekrar dene",
    empty: "En az bir çalışan seçin.",
    missing: "Çalışan kullanılamıyor",
    search: "Çalışan ara",
  },
};
