//! Authoritative AirHub groups and their atomic weekly recurrence rules.

use std::collections::{BTreeMap, BTreeSet};

use airhop_core::{TrialPolicy, Weekday};
use buzz_core::TenantContext;
use chrono::{DateTime, Datelike, NaiveDate, NaiveTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sqlx::Row;
use uuid::Uuid;

use super::{
    append_domain_event, commit_command, insert_pending_command, ActorKind, AirhopActor,
    AirhopCommand, CommandInsertOutcome, CommandStatus, NewAirhopCommand, NewDomainEvent,
    PrivacyClass,
};
use crate::{Db, DbError, Result};

const CREATE_GROUP_COMMAND_TYPE: &str = "CreateGroup";
const PUT_GROUP_COMMAND_TYPE: &str = "PutGroup";
const MAX_RULES: usize = 128;
const MAX_TEACHERS: usize = 128;

/// Lifecycle of an operational group.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GroupStatus {
    /// Available in the operational schedule.
    Active,
    /// Retained for history but unavailable for new operational assignments.
    Archived,
}

impl GroupStatus {
    const fn as_db_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Archived => "archived",
        }
    }

    fn from_db(value: &str) -> Result<Self> {
        match value {
            "active" => Ok(Self::Active),
            "archived" => Ok(Self::Archived),
            other => Err(DbError::InvalidData(format!(
                "unknown AirHub group status {other:?}"
            ))),
        }
    }
}

/// Lifecycle of a recurrence rule.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecurrenceRuleStatus {
    /// Included in future schedule materialization.
    Active,
    /// Retained for stable historical lesson references.
    Archived,
}

impl RecurrenceRuleStatus {
    fn from_db(value: &str) -> Result<Self> {
        match value {
            "active" => Ok(Self::Active),
            "archived" => Ok(Self::Archived),
            other => Err(DbError::InvalidData(format!(
                "unknown AirHub recurrence-rule status {other:?}"
            ))),
        }
    }
}

/// Mutable fields of one group, shared by create and replacement commands.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GroupDefinition {
    /// Parent branch.
    pub branch_id: Uuid,
    /// Optional default room inside the parent branch.
    pub room_id: Option<Uuid>,
    /// Human-readable group name.
    pub name: String,
    /// Optional staff-facing description.
    pub description: Option<String>,
    /// Default teachers.
    pub teacher_ids: Vec<Uuid>,
    /// Inclusive minimum age in months.
    pub min_age_months: Option<i32>,
    /// Inclusive maximum age in months.
    pub max_age_months: Option<i32>,
    /// Default capacity, or unbounded when absent.
    pub capacity: Option<i32>,
    /// Group-specific trial policy.
    pub trial_policy_override: Option<TrialPolicy>,
    /// Group-specific attendance setting.
    pub track_attendance_override: Option<bool>,
    /// Group-specific one-off visit setting.
    pub allow_single_visits_override: Option<bool>,
    /// Desired group lifecycle.
    pub status: GroupStatus,
}

/// One active recurrence rule supplied as part of an atomic group command.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecurrenceRuleInput {
    /// Existing server-owned rule id, or absent for a newly allocated rule.
    pub id: Option<Uuid>,
    /// Inclusive first original date.
    pub starts_on: NaiveDate,
    /// Inclusive last original date.
    pub ends_on: NaiveDate,
    /// Weekdays generated by this rule.
    pub weekdays: Vec<Weekday>,
    /// Local lesson start.
    pub start_time: NaiveTime,
    /// Local lesson end.
    pub end_time: NaiveTime,
    /// Optional branch replacement.
    pub branch_id_override: Option<Uuid>,
    /// Whether the room override is explicit rather than inherited.
    pub room_override_set: bool,
    /// Explicit room replacement, or `None` to clear when the override is set.
    pub room_id_override: Option<Uuid>,
    /// Optional teacher-list replacement.
    pub teacher_ids_override: Option<Vec<Uuid>>,
    /// Whether the capacity override is explicit rather than inherited.
    pub capacity_override_set: bool,
    /// Explicit capacity replacement, or `None` to clear when the override is set.
    pub capacity_override: Option<i32>,
    /// Rule-specific trial policy.
    pub trial_policy_override: Option<TrialPolicy>,
}

/// Server-authoritative group projection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AirhopGroup {
    /// Server-owned group id.
    pub id: Uuid,
    /// Server-resolved organization id.
    pub organization_id: Uuid,
    /// Parent branch.
    pub branch_id: Uuid,
    /// Optional default room.
    pub room_id: Option<Uuid>,
    /// Human-readable name.
    pub name: String,
    /// Optional staff-facing description.
    pub description: Option<String>,
    /// Default teachers.
    pub teacher_ids: Vec<Uuid>,
    /// Inclusive minimum age in months.
    pub min_age_months: Option<i32>,
    /// Inclusive maximum age in months.
    pub max_age_months: Option<i32>,
    /// Default capacity.
    pub capacity: Option<i32>,
    /// Group-specific trial policy.
    pub trial_policy_override: Option<TrialPolicy>,
    /// Group-specific attendance setting.
    pub track_attendance_override: Option<bool>,
    /// Group-specific one-off visit setting.
    pub allow_single_visits_override: Option<bool>,
    /// Operational lifecycle.
    pub status: GroupStatus,
    /// Aggregate optimistic version.
    pub version: i64,
    /// Creation instant.
    pub created_at: DateTime<Utc>,
    /// Last update instant.
    pub updated_at: DateTime<Utc>,
}

/// Server-authoritative recurrence-rule projection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AirhopRecurrenceRule {
    /// Server-owned rule id.
    pub id: Uuid,
    /// Server-resolved organization id.
    pub organization_id: Uuid,
    /// Owning group.
    pub group_id: Uuid,
    /// Inclusive first original date.
    pub starts_on: NaiveDate,
    /// Inclusive last original date.
    pub ends_on: NaiveDate,
    /// Generated weekdays.
    pub weekdays: Vec<Weekday>,
    /// Local lesson start.
    pub start_time: NaiveTime,
    /// Local lesson end.
    pub end_time: NaiveTime,
    /// Optional branch replacement.
    pub branch_id_override: Option<Uuid>,
    /// Whether the room override is explicit.
    pub room_override_set: bool,
    /// Explicit room replacement, or clear when absent and set.
    pub room_id_override: Option<Uuid>,
    /// Optional teacher-list replacement.
    pub teacher_ids_override: Option<Vec<Uuid>>,
    /// Whether the capacity override is explicit.
    pub capacity_override_set: bool,
    /// Explicit capacity replacement, or clear when absent and set.
    pub capacity_override: Option<i32>,
    /// Rule-specific trial policy.
    pub trial_policy_override: Option<TrialPolicy>,
    /// Operational lifecycle.
    pub status: RecurrenceRuleStatus,
    /// Row version, exposed for cache revision accounting.
    pub version: i64,
    /// Creation instant.
    pub created_at: DateTime<Utc>,
    /// Last update instant.
    pub updated_at: DateTime<Utc>,
}

/// Idempotent input for creating a group and all its initial rules.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateGroupInput {
    /// Initial group fields. New groups must be active.
    pub group: GroupDefinition,
    /// Initial active recurrence rules.
    pub active_rules: Vec<RecurrenceRuleInput>,
    /// Keyed digest of the HTTP idempotency key.
    pub idempotency_digest: [u8; 32],
    /// Hash of method, path, and canonical HTTP body.
    pub request_hash: [u8; 32],
    /// Verified staff attribution.
    pub actor: AirhopActor,
}

/// Full optimistic replacement of a group and its active recurrence rules.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PutGroupInput {
    /// Server-owned group id.
    pub group_id: Uuid,
    /// Aggregate version observed by the staff client.
    pub expected_version: i64,
    /// Replacement group fields.
    pub group: GroupDefinition,
    /// Complete replacement set of active recurrence rules.
    pub active_rules: Vec<RecurrenceRuleInput>,
    /// Keyed digest of the HTTP idempotency key.
    pub idempotency_digest: [u8; 32],
    /// Hash of method, path, and canonical HTTP body.
    pub request_hash: [u8; 32],
    /// Verified staff attribution.
    pub actor: AirhopActor,
}

/// Result of a group aggregate command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GroupMutationOutcome {
    /// Affected group.
    pub group_id: Uuid,
    /// New or replayed aggregate version.
    pub version: i64,
    /// True when a committed command receipt was replayed.
    pub replayed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct StoredGroupMutationResult {
    group_id: Uuid,
    version: i64,
}

#[derive(Debug)]
struct CurrentGroup {
    branch_id: Uuid,
    room_id: Option<Uuid>,
    status: GroupStatus,
    version: i64,
}

impl Db {
    /// Lists all active and archived groups for the host-resolved tenant.
    pub async fn list_airhop_groups(&self, tenant: &TenantContext) -> Result<Vec<AirhopGroup>> {
        let organization_id = resolve_active_organization(&self.pool, tenant).await?;
        let rows = sqlx::query(
            "SELECT id, organization_id, branch_id, room_id, name, description, \
                    min_age_months, max_age_months, capacity, trial_policy_override, \
                    track_attendance_override, allow_single_visits_override, status, \
                    version, created_at, updated_at \
             FROM airhop_groups \
             WHERE community_id = $1 AND organization_id = $2 \
             ORDER BY CASE status WHEN 'active' THEN 0 ELSE 1 END, lower(name), id",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .fetch_all(&self.pool)
        .await?;
        let mut groups = rows
            .into_iter()
            .map(parse_group_row)
            .collect::<Result<Vec<_>>>()?;
        let positions = groups
            .iter()
            .enumerate()
            .map(|(index, group)| (group.id, index))
            .collect::<BTreeMap<_, _>>();
        let teachers = sqlx::query(
            "SELECT group_id, teacher_id FROM airhop_group_teachers \
             WHERE community_id = $1 AND organization_id = $2 \
             ORDER BY group_id, teacher_id",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .fetch_all(&self.pool)
        .await?;
        for row in teachers {
            let group_id: Uuid = row.try_get("group_id")?;
            let index = positions.get(&group_id).ok_or_else(|| {
                DbError::InvalidData("AirHub group teacher has no group".to_owned())
            })?;
            groups[*index].teacher_ids.push(row.try_get("teacher_id")?);
        }
        Ok(groups)
    }

    /// Lists all active and archived recurrence rules for the tenant's groups.
    pub async fn list_airhop_recurrence_rules(
        &self,
        tenant: &TenantContext,
    ) -> Result<Vec<AirhopRecurrenceRule>> {
        let organization_id = resolve_active_organization(&self.pool, tenant).await?;
        let rows = sqlx::query(
            "SELECT id, organization_id, group_id, starts_on, ends_on, start_time, end_time, \
                    branch_id_override, room_override_set, room_id_override, \
                    teacher_override_set, capacity_override_set, capacity_override, \
                    trial_policy_override, status, version, created_at, updated_at \
             FROM airhop_recurrence_rules \
             WHERE community_id = $1 AND organization_id = $2 \
             ORDER BY group_id, CASE status WHEN 'active' THEN 0 ELSE 1 END, starts_on, start_time, id",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .fetch_all(&self.pool)
        .await?;
        let mut rules = rows
            .into_iter()
            .map(parse_rule_row)
            .collect::<Result<Vec<_>>>()?;
        let positions = rules
            .iter()
            .enumerate()
            .map(|(index, rule)| (rule.id, index))
            .collect::<BTreeMap<_, _>>();
        let weekdays = sqlx::query(
            "SELECT recurrence_rule_id, weekday FROM airhop_recurrence_weekdays \
             WHERE community_id = $1 AND organization_id = $2 \
             ORDER BY recurrence_rule_id, weekday",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .fetch_all(&self.pool)
        .await?;
        for row in weekdays {
            let rule_id: Uuid = row.try_get("recurrence_rule_id")?;
            let index = positions.get(&rule_id).ok_or_else(|| {
                DbError::InvalidData("AirHub recurrence weekday has no rule".to_owned())
            })?;
            rules[*index]
                .weekdays
                .push(parse_weekday(row.try_get("weekday")?)?);
        }
        let teachers = sqlx::query(
            "SELECT recurrence_rule_id, teacher_id FROM airhop_recurrence_teachers \
             WHERE community_id = $1 AND organization_id = $2 \
             ORDER BY recurrence_rule_id, teacher_id",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .fetch_all(&self.pool)
        .await?;
        for row in teachers {
            let rule_id: Uuid = row.try_get("recurrence_rule_id")?;
            let index = positions.get(&rule_id).ok_or_else(|| {
                DbError::InvalidData("AirHub recurrence teacher has no rule".to_owned())
            })?;
            rules[*index]
                .teacher_ids_override
                .get_or_insert_with(Vec::new)
                .push(row.try_get("teacher_id")?);
        }
        Ok(rules)
    }

    /// Creates a group, its active rules, audit event, and receipt atomically.
    pub async fn create_airhop_group(
        &self,
        tenant: &TenantContext,
        input: &CreateGroupInput,
    ) -> Result<GroupMutationOutcome> {
        validate_create_input(input)?;
        let mut transaction = self.pool.begin().await?;
        let organization_id = resolve_active_organization(&mut *transaction, tenant).await?;
        let command = match insert_pending_command(
            &mut transaction,
            tenant,
            &NewAirhopCommand {
                id: Uuid::new_v4(),
                organization_id,
                command_type: CREATE_GROUP_COMMAND_TYPE.to_owned(),
                idempotency_digest: input.idempotency_digest,
                request_hash: input.request_hash,
                actor: input.actor.clone(),
                correlation_id: Uuid::new_v4(),
            },
        )
        .await?
        {
            CommandInsertOutcome::Inserted(command) => command,
            CommandInsertOutcome::Existing(command) => {
                return replay_mutation(transaction, command).await;
            }
        };
        require_active_branch(
            &mut transaction,
            tenant,
            organization_id,
            input.group.branch_id,
        )
        .await?;
        validate_group_links(
            &mut transaction,
            tenant,
            organization_id,
            &input.group,
            &BTreeSet::new(),
            None,
        )
        .await?;
        for rule in &input.active_rules {
            validate_rule_links(
                &mut transaction,
                tenant,
                organization_id,
                &input.group,
                rule,
            )
            .await?;
        }
        let group_id = Uuid::new_v4();
        let occurred_at: DateTime<Utc> = sqlx::query_scalar("SELECT now()")
            .fetch_one(&mut *transaction)
            .await?;
        let trial_policy = optional_json(input.group.trial_policy_override.as_ref())?;
        sqlx::query(
            "INSERT INTO airhop_groups (community_id, organization_id, id, branch_id, \
                 room_id, name, description, min_age_months, max_age_months, capacity, \
                 trial_policy_override, track_attendance_override, \
                 allow_single_visits_override, status, created_at, updated_at) \
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $15)",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(group_id)
        .bind(input.group.branch_id)
        .bind(input.group.room_id)
        .bind(input.group.name.trim())
        .bind(clean_optional(&input.group.description))
        .bind(input.group.min_age_months)
        .bind(input.group.max_age_months)
        .bind(input.group.capacity)
        .bind(trial_policy)
        .bind(input.group.track_attendance_override)
        .bind(input.group.allow_single_visits_override)
        .bind(input.group.status.as_db_str())
        .bind(occurred_at)
        .execute(&mut *transaction)
        .await?;
        replace_group_teachers(
            &mut transaction,
            tenant,
            organization_id,
            group_id,
            &input.group.teacher_ids,
        )
        .await?;
        for rule in &input.active_rules {
            insert_rule(
                &mut transaction,
                tenant,
                organization_id,
                group_id,
                rule,
                occurred_at,
            )
            .await?;
        }
        append_domain_event(
            &mut transaction,
            tenant,
            &NewDomainEvent {
                id: Uuid::new_v4(),
                organization_id,
                stream_type: "group".to_owned(),
                stream_id: group_id,
                stream_version: 1,
                event_type: "airhop.group.created.v1".to_owned(),
                schema_version: 1,
                occurred_at,
                actor: input.actor.clone(),
                causation_id: command.id,
                correlation_id: command.correlation_id,
                payload: json!({
                    "groupId": group_id,
                    "branchId": input.group.branch_id,
                    "roomId": input.group.room_id,
                    "activeRuleCount": input.active_rules.len(),
                }),
                privacy_class: PrivacyClass::Operational,
            },
        )
        .await?;
        finish_mutation(
            transaction,
            tenant,
            organization_id,
            command.id,
            group_id,
            1,
        )
        .await
    }

    /// Replaces a group and its active recurrence rules with one optimistic token.
    pub async fn put_airhop_group(
        &self,
        tenant: &TenantContext,
        input: &PutGroupInput,
    ) -> Result<GroupMutationOutcome> {
        validate_put_input(input)?;
        let mut transaction = self.pool.begin().await?;
        let organization_id = resolve_active_organization(&mut *transaction, tenant).await?;
        let command = match insert_pending_command(
            &mut transaction,
            tenant,
            &NewAirhopCommand {
                id: Uuid::new_v4(),
                organization_id,
                command_type: PUT_GROUP_COMMAND_TYPE.to_owned(),
                idempotency_digest: input.idempotency_digest,
                request_hash: input.request_hash,
                actor: input.actor.clone(),
                correlation_id: Uuid::new_v4(),
            },
        )
        .await?
        {
            CommandInsertOutcome::Inserted(command) => command,
            CommandInsertOutcome::Existing(command) => {
                return replay_mutation(transaction, command).await;
            }
        };
        let current =
            load_current_group(&mut transaction, tenant, organization_id, input.group_id).await?;
        if current.version != input.expected_version {
            return Err(DbError::AirhopVersionConflict);
        }
        if current.branch_id != input.group.branch_id
            || (current.status == GroupStatus::Archived
                && input.group.status == GroupStatus::Active)
        {
            require_active_branch(
                &mut transaction,
                tenant,
                organization_id,
                input.group.branch_id,
            )
            .await?;
        }
        let current_teachers =
            load_group_teacher_ids(&mut transaction, tenant, organization_id, input.group_id)
                .await?;
        validate_group_links(
            &mut transaction,
            tenant,
            organization_id,
            &input.group,
            &current_teachers,
            current.room_id,
        )
        .await?;
        let existing_rule_ids =
            load_group_rule_ids(&mut transaction, tenant, organization_id, input.group_id).await?;
        for rule in &input.active_rules {
            if let Some(rule_id) = rule.id {
                if !existing_rule_ids.contains(&rule_id) {
                    return Err(DbError::InvalidData(
                        "AirHub recurrence rule belongs to another group".to_owned(),
                    ));
                }
                protect_booked_original_dates(
                    &mut transaction,
                    tenant,
                    organization_id,
                    rule_id,
                    rule,
                )
                .await?;
            }
            validate_rule_links(
                &mut transaction,
                tenant,
                organization_id,
                &input.group,
                rule,
            )
            .await?;
        }
        protect_enrollment_selections(
            &mut transaction,
            tenant,
            organization_id,
            input.group_id,
            &input.active_rules,
        )
        .await?;
        let occurred_at: DateTime<Utc> = sqlx::query_scalar("SELECT now()")
            .fetch_one(&mut *transaction)
            .await?;
        let trial_policy = optional_json(input.group.trial_policy_override.as_ref())?;
        let version: i64 = sqlx::query_scalar(
            "UPDATE airhop_groups SET branch_id = $4, room_id = $5, name = $6, \
                 description = $7, min_age_months = $8, max_age_months = $9, capacity = $10, \
                 trial_policy_override = $11, track_attendance_override = $12, \
                 allow_single_visits_override = $13, status = $14, version = version + 1, \
                 updated_at = $15 \
             WHERE community_id = $1 AND organization_id = $2 AND id = $3 AND version = $16 \
             RETURNING version",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(input.group_id)
        .bind(input.group.branch_id)
        .bind(input.group.room_id)
        .bind(input.group.name.trim())
        .bind(clean_optional(&input.group.description))
        .bind(input.group.min_age_months)
        .bind(input.group.max_age_months)
        .bind(input.group.capacity)
        .bind(trial_policy)
        .bind(input.group.track_attendance_override)
        .bind(input.group.allow_single_visits_override)
        .bind(input.group.status.as_db_str())
        .bind(occurred_at)
        .bind(input.expected_version)
        .fetch_optional(&mut *transaction)
        .await?
        .ok_or(DbError::AirhopVersionConflict)?;
        replace_group_teachers(
            &mut transaction,
            tenant,
            organization_id,
            input.group_id,
            &input.group.teacher_ids,
        )
        .await?;
        let mut retained = BTreeSet::new();
        for rule in &input.active_rules {
            let rule_id = match rule.id {
                Some(rule_id) => {
                    update_rule(
                        &mut transaction,
                        tenant,
                        organization_id,
                        input.group_id,
                        rule_id,
                        rule,
                        occurred_at,
                    )
                    .await?;
                    rule_id
                }
                None => {
                    insert_rule(
                        &mut transaction,
                        tenant,
                        organization_id,
                        input.group_id,
                        rule,
                        occurred_at,
                    )
                    .await?
                }
            };
            retained.insert(rule_id);
        }
        archive_omitted_rules(
            &mut transaction,
            tenant,
            organization_id,
            input.group_id,
            &retained,
            occurred_at,
        )
        .await?;
        let event_type = match (current.status, input.group.status) {
            (GroupStatus::Active, GroupStatus::Archived) => "airhop.group.archived.v1",
            (GroupStatus::Archived, GroupStatus::Active) => "airhop.group.restored.v1",
            _ => "airhop.group.updated.v1",
        };
        append_domain_event(
            &mut transaction,
            tenant,
            &NewDomainEvent {
                id: Uuid::new_v4(),
                organization_id,
                stream_type: "group".to_owned(),
                stream_id: input.group_id,
                stream_version: version,
                event_type: event_type.to_owned(),
                schema_version: 1,
                occurred_at,
                actor: input.actor.clone(),
                causation_id: command.id,
                correlation_id: command.correlation_id,
                payload: json!({
                    "groupId": input.group_id,
                    "branchId": input.group.branch_id,
                    "roomId": input.group.room_id,
                    "status": input.group.status,
                    "activeRuleCount": input.active_rules.len(),
                }),
                privacy_class: PrivacyClass::Operational,
            },
        )
        .await?;
        finish_mutation(
            transaction,
            tenant,
            organization_id,
            command.id,
            input.group_id,
            version,
        )
        .await
    }
}

async fn resolve_active_organization<'e, E>(executor: E, tenant: &TenantContext) -> Result<Uuid>
where
    E: sqlx::Executor<'e, Database = sqlx::Postgres>,
{
    sqlx::query_scalar(
        "SELECT id FROM airhop_organizations WHERE community_id = $1 AND status = 'active'",
    )
    .bind(tenant.community().as_uuid())
    .fetch_optional(executor)
    .await?
    .ok_or_else(|| DbError::NotFound("active AirHub organization".to_owned()))
}

async fn load_current_group(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
) -> Result<CurrentGroup> {
    let row = sqlx::query(
        "SELECT branch_id, room_id, status, version FROM airhop_groups \
         WHERE community_id = $1 AND organization_id = $2 AND id = $3 FOR UPDATE",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .fetch_optional(&mut **transaction)
    .await?
    .ok_or_else(|| DbError::NotFound("AirHub group".to_owned()))?;
    Ok(CurrentGroup {
        branch_id: row.try_get("branch_id")?,
        room_id: row.try_get("room_id")?,
        status: GroupStatus::from_db(row.try_get("status")?)?,
        version: row.try_get("version")?,
    })
}

async fn require_active_branch(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    branch_id: Uuid,
) -> Result<()> {
    let found: bool = sqlx::query_scalar(
        "SELECT EXISTS(SELECT 1 FROM airhop_branches \
         WHERE community_id = $1 AND organization_id = $2 AND id = $3 AND status = 'active')",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(branch_id)
    .fetch_one(&mut **transaction)
    .await?;
    if found {
        Ok(())
    } else {
        Err(DbError::NotFound("active AirHub branch".to_owned()))
    }
}

async fn validate_group_links(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group: &GroupDefinition,
    current_teacher_ids: &BTreeSet<Uuid>,
    current_room_id: Option<Uuid>,
) -> Result<()> {
    if let Some(room_id) = group.room_id {
        let row = sqlx::query(
            "SELECT branch_id, status FROM airhop_rooms \
             WHERE community_id = $1 AND organization_id = $2 AND id = $3 FOR SHARE",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(room_id)
        .fetch_optional(&mut **transaction)
        .await?
        .ok_or_else(|| DbError::NotFound("AirHub room".to_owned()))?;
        let branch_id: Uuid = row.try_get("branch_id")?;
        let status: String = row.try_get("status")?;
        if branch_id != group.branch_id || (status != "active" && current_room_id != Some(room_id))
        {
            return Err(DbError::NotFound(
                "active AirHub room in group branch".to_owned(),
            ));
        }
    }
    validate_teacher_ids(
        transaction,
        tenant,
        organization_id,
        &group.teacher_ids,
        current_teacher_ids,
    )
    .await
}

async fn validate_rule_links(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group: &GroupDefinition,
    rule: &RecurrenceRuleInput,
) -> Result<()> {
    let effective_branch = rule.branch_id_override.unwrap_or(group.branch_id);
    if rule.branch_id_override.is_some() {
        require_active_branch(transaction, tenant, organization_id, effective_branch).await?;
    }
    if rule.room_override_set {
        if let Some(room_id) = rule.room_id_override {
            let found: bool = sqlx::query_scalar(
                "SELECT EXISTS(SELECT 1 FROM airhop_rooms \
                 WHERE community_id = $1 AND organization_id = $2 AND id = $3 \
                   AND branch_id = $4 AND status = 'active')",
            )
            .bind(tenant.community().as_uuid())
            .bind(organization_id)
            .bind(room_id)
            .bind(effective_branch)
            .fetch_one(&mut **transaction)
            .await?;
            if !found {
                return Err(DbError::NotFound(
                    "active AirHub recurrence room".to_owned(),
                ));
            }
        }
    } else if rule.room_id_override.is_some() {
        return Err(DbError::InvalidData(
            "AirHub recurrence room override is inconsistent".to_owned(),
        ));
    }
    if let Some(teacher_ids) = &rule.teacher_ids_override {
        validate_teacher_ids(
            transaction,
            tenant,
            organization_id,
            teacher_ids,
            &BTreeSet::new(),
        )
        .await?;
    }
    Ok(())
}

async fn validate_teacher_ids(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    teacher_ids: &[Uuid],
    allowed_archived: &BTreeSet<Uuid>,
) -> Result<()> {
    for teacher_id in teacher_ids {
        let status: String = sqlx::query_scalar(
            "SELECT status FROM airhop_teachers \
             WHERE community_id = $1 AND organization_id = $2 AND id = $3 FOR SHARE",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(teacher_id)
        .fetch_optional(&mut **transaction)
        .await?
        .ok_or_else(|| DbError::NotFound("AirHub teacher".to_owned()))?;
        if status != "active" && !allowed_archived.contains(teacher_id) {
            return Err(DbError::NotFound("active AirHub teacher".to_owned()));
        }
    }
    Ok(())
}

async fn load_group_teacher_ids(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
) -> Result<BTreeSet<Uuid>> {
    Ok(sqlx::query_scalar(
        "SELECT teacher_id FROM airhop_group_teachers \
         WHERE community_id = $1 AND organization_id = $2 AND group_id = $3",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .fetch_all(&mut **transaction)
    .await?
    .into_iter()
    .collect())
}

async fn load_group_rule_ids(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
) -> Result<BTreeSet<Uuid>> {
    Ok(sqlx::query_scalar(
        "SELECT id FROM airhop_recurrence_rules \
         WHERE community_id = $1 AND organization_id = $2 AND group_id = $3 FOR UPDATE",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .fetch_all(&mut **transaction)
    .await?
    .into_iter()
    .collect())
}

async fn protect_booked_original_dates(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    rule_id: Uuid,
    replacement: &RecurrenceRuleInput,
) -> Result<()> {
    let dates: Vec<NaiveDate> = sqlx::query_scalar(
        "SELECT original_date FROM airhop_bookings \
         WHERE community_id = $1 AND organization_id = $2 AND recurrence_rule_id = $3",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(rule_id)
    .fetch_all(&mut **transaction)
    .await?;
    if dates.iter().any(|date| {
        *date < replacement.starts_on
            || *date > replacement.ends_on
            || !replacement
                .weekdays
                .contains(&Weekday::from(date.weekday()))
    }) {
        return Err(DbError::InvalidData(
            "AirHub recurrence update would exclude a booked occurrence".to_owned(),
        ));
    }
    Ok(())
}

async fn protect_enrollment_selections(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
    active_rules: &[RecurrenceRuleInput],
) -> Result<()> {
    let rows = sqlx::query(
        "SELECT selection.recurrence_rule_id, selection.weekday \
         FROM airhop_enrollment_schedule selection \
         JOIN airhop_enrollments enrollment \
           ON enrollment.community_id = selection.community_id \
          AND enrollment.organization_id = selection.organization_id \
          AND enrollment.id = selection.enrollment_id \
         WHERE selection.community_id = $1 AND selection.organization_id = $2 \
           AND selection.group_id = $3 AND enrollment.status = 'active'",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .fetch_all(&mut **transaction)
    .await?;
    for row in rows {
        let rule_id: Uuid = row.try_get("recurrence_rule_id")?;
        let weekday = parse_weekday(row.try_get("weekday")?)?;
        let valid = active_rules
            .iter()
            .find(|rule| rule.id == Some(rule_id))
            .is_some_and(|rule| rule.weekdays.contains(&weekday));
        if !valid {
            return Err(DbError::InvalidData(
                "AirHub recurrence update would invalidate an active enrollment".to_owned(),
            ));
        }
    }
    Ok(())
}

async fn replace_group_teachers(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
    teacher_ids: &[Uuid],
) -> Result<()> {
    sqlx::query(
        "DELETE FROM airhop_group_teachers \
         WHERE community_id = $1 AND organization_id = $2 AND group_id = $3",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .execute(&mut **transaction)
    .await?;
    for teacher_id in teacher_ids {
        sqlx::query(
            "INSERT INTO airhop_group_teachers \
             (community_id, organization_id, group_id, teacher_id) VALUES ($1, $2, $3, $4)",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(group_id)
        .bind(teacher_id)
        .execute(&mut **transaction)
        .await?;
    }
    Ok(())
}

async fn insert_rule(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
    rule: &RecurrenceRuleInput,
    occurred_at: DateTime<Utc>,
) -> Result<Uuid> {
    let rule_id = Uuid::new_v4();
    let trial_policy = optional_json(rule.trial_policy_override.as_ref())?;
    sqlx::query(
        "INSERT INTO airhop_recurrence_rules (community_id, organization_id, id, group_id, \
             starts_on, ends_on, start_time, end_time, branch_id_override, room_override_set, \
             room_id_override, teacher_override_set, capacity_override_set, capacity_override, \
             trial_policy_override, status, created_at, updated_at) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, \
                 'active', $16, $16)",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(rule_id)
    .bind(group_id)
    .bind(rule.starts_on)
    .bind(rule.ends_on)
    .bind(rule.start_time)
    .bind(rule.end_time)
    .bind(rule.branch_id_override)
    .bind(rule.room_override_set)
    .bind(rule.room_id_override)
    .bind(rule.teacher_ids_override.is_some())
    .bind(rule.capacity_override_set)
    .bind(rule.capacity_override)
    .bind(trial_policy)
    .bind(occurred_at)
    .execute(&mut **transaction)
    .await?;
    replace_rule_children(transaction, tenant, organization_id, rule_id, rule).await?;
    Ok(rule_id)
}

async fn update_rule(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
    rule_id: Uuid,
    rule: &RecurrenceRuleInput,
    occurred_at: DateTime<Utc>,
) -> Result<()> {
    let trial_policy = optional_json(rule.trial_policy_override.as_ref())?;
    let updated = sqlx::query(
        "UPDATE airhop_recurrence_rules SET starts_on = $5, ends_on = $6, start_time = $7, \
             end_time = $8, branch_id_override = $9, room_override_set = $10, \
             room_id_override = $11, teacher_override_set = $12, capacity_override_set = $13, \
             capacity_override = $14, trial_policy_override = $15, status = 'active', \
             version = version + 1, updated_at = $16 \
         WHERE community_id = $1 AND organization_id = $2 AND group_id = $3 AND id = $4",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .bind(rule_id)
    .bind(rule.starts_on)
    .bind(rule.ends_on)
    .bind(rule.start_time)
    .bind(rule.end_time)
    .bind(rule.branch_id_override)
    .bind(rule.room_override_set)
    .bind(rule.room_id_override)
    .bind(rule.teacher_ids_override.is_some())
    .bind(rule.capacity_override_set)
    .bind(rule.capacity_override)
    .bind(trial_policy)
    .bind(occurred_at)
    .execute(&mut **transaction)
    .await?;
    if updated.rows_affected() != 1 {
        return Err(DbError::NotFound("AirHub recurrence rule".to_owned()));
    }
    replace_rule_children(transaction, tenant, organization_id, rule_id, rule).await
}

async fn replace_rule_children(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    rule_id: Uuid,
    rule: &RecurrenceRuleInput,
) -> Result<()> {
    sqlx::query(
        "DELETE FROM airhop_recurrence_weekdays \
         WHERE community_id = $1 AND organization_id = $2 AND recurrence_rule_id = $3",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(rule_id)
    .execute(&mut **transaction)
    .await?;
    for weekday in &rule.weekdays {
        sqlx::query(
            "INSERT INTO airhop_recurrence_weekdays \
             (community_id, organization_id, recurrence_rule_id, weekday) VALUES ($1, $2, $3, $4)",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(rule_id)
        .bind(weekday_str(*weekday))
        .execute(&mut **transaction)
        .await?;
    }
    sqlx::query(
        "DELETE FROM airhop_recurrence_teachers \
         WHERE community_id = $1 AND organization_id = $2 AND recurrence_rule_id = $3",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(rule_id)
    .execute(&mut **transaction)
    .await?;
    if let Some(teacher_ids) = &rule.teacher_ids_override {
        for teacher_id in teacher_ids {
            sqlx::query(
                "INSERT INTO airhop_recurrence_teachers \
                 (community_id, organization_id, recurrence_rule_id, teacher_id) \
                 VALUES ($1, $2, $3, $4)",
            )
            .bind(tenant.community().as_uuid())
            .bind(organization_id)
            .bind(rule_id)
            .bind(teacher_id)
            .execute(&mut **transaction)
            .await?;
        }
    }
    Ok(())
}

async fn archive_omitted_rules(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    group_id: Uuid,
    retained: &BTreeSet<Uuid>,
    occurred_at: DateTime<Utc>,
) -> Result<()> {
    let active_ids: Vec<Uuid> = sqlx::query_scalar(
        "SELECT id FROM airhop_recurrence_rules \
         WHERE community_id = $1 AND organization_id = $2 AND group_id = $3 AND status = 'active'",
    )
    .bind(tenant.community().as_uuid())
    .bind(organization_id)
    .bind(group_id)
    .fetch_all(&mut **transaction)
    .await?;
    for rule_id in active_ids {
        if retained.contains(&rule_id) {
            continue;
        }
        sqlx::query(
            "UPDATE airhop_recurrence_rules SET status = 'archived', version = version + 1, \
                 updated_at = $4 \
             WHERE community_id = $1 AND organization_id = $2 AND id = $3",
        )
        .bind(tenant.community().as_uuid())
        .bind(organization_id)
        .bind(rule_id)
        .bind(occurred_at)
        .execute(&mut **transaction)
        .await?;
    }
    Ok(())
}

async fn finish_mutation(
    mut transaction: sqlx::Transaction<'_, sqlx::Postgres>,
    tenant: &TenantContext,
    organization_id: Uuid,
    command_id: Uuid,
    group_id: Uuid,
    version: i64,
) -> Result<GroupMutationOutcome> {
    let stored = StoredGroupMutationResult { group_id, version };
    commit_command(
        &mut transaction,
        tenant,
        organization_id,
        command_id,
        &serde_json::to_value(&stored)?,
    )
    .await?;
    transaction.commit().await?;
    Ok(GroupMutationOutcome {
        group_id,
        version,
        replayed: false,
    })
}

async fn replay_mutation(
    transaction: sqlx::Transaction<'_, sqlx::Postgres>,
    command: AirhopCommand,
) -> Result<GroupMutationOutcome> {
    match command.status {
        CommandStatus::Pending => Err(DbError::AirhopCommandInProgress),
        CommandStatus::Failed => Err(DbError::AirhopCommandPreviouslyFailed),
        CommandStatus::Committed => {
            let stored: StoredGroupMutationResult =
                serde_json::from_value(command.result.ok_or_else(|| {
                    DbError::InvalidData("committed AirHub command has no result".to_owned())
                })?)?;
            transaction.commit().await?;
            Ok(GroupMutationOutcome {
                group_id: stored.group_id,
                version: stored.version,
                replayed: true,
            })
        }
    }
}

fn parse_group_row(row: sqlx::postgres::PgRow) -> Result<AirhopGroup> {
    let trial_policy: Option<Value> = row.try_get("trial_policy_override")?;
    Ok(AirhopGroup {
        id: row.try_get("id")?,
        organization_id: row.try_get("organization_id")?,
        branch_id: row.try_get("branch_id")?,
        room_id: row.try_get("room_id")?,
        name: row.try_get("name")?,
        description: row.try_get("description")?,
        teacher_ids: Vec::new(),
        min_age_months: row.try_get("min_age_months")?,
        max_age_months: row.try_get("max_age_months")?,
        capacity: row.try_get("capacity")?,
        trial_policy_override: trial_policy.map(serde_json::from_value).transpose()?,
        track_attendance_override: row.try_get("track_attendance_override")?,
        allow_single_visits_override: row.try_get("allow_single_visits_override")?,
        status: GroupStatus::from_db(row.try_get("status")?)?,
        version: row.try_get("version")?,
        created_at: row.try_get("created_at")?,
        updated_at: row.try_get("updated_at")?,
    })
}

fn parse_rule_row(row: sqlx::postgres::PgRow) -> Result<AirhopRecurrenceRule> {
    let trial_policy: Option<Value> = row.try_get("trial_policy_override")?;
    let teacher_override_set: bool = row.try_get("teacher_override_set")?;
    Ok(AirhopRecurrenceRule {
        id: row.try_get("id")?,
        organization_id: row.try_get("organization_id")?,
        group_id: row.try_get("group_id")?,
        starts_on: row.try_get("starts_on")?,
        ends_on: row.try_get("ends_on")?,
        weekdays: Vec::new(),
        start_time: row.try_get("start_time")?,
        end_time: row.try_get("end_time")?,
        branch_id_override: row.try_get("branch_id_override")?,
        room_override_set: row.try_get("room_override_set")?,
        room_id_override: row.try_get("room_id_override")?,
        teacher_ids_override: teacher_override_set.then(Vec::new),
        capacity_override_set: row.try_get("capacity_override_set")?,
        capacity_override: row.try_get("capacity_override")?,
        trial_policy_override: trial_policy.map(serde_json::from_value).transpose()?,
        status: RecurrenceRuleStatus::from_db(row.try_get("status")?)?,
        version: row.try_get("version")?,
        created_at: row.try_get("created_at")?,
        updated_at: row.try_get("updated_at")?,
    })
}

fn validate_create_input(input: &CreateGroupInput) -> Result<()> {
    if input.group.status != GroupStatus::Active
        || input.active_rules.iter().any(|rule| rule.id.is_some())
    {
        return Err(DbError::InvalidData(
            "new AirHub group or recurrence identity is invalid".to_owned(),
        ));
    }
    validate_common(&input.group, &input.active_rules, &input.actor)
}

fn validate_put_input(input: &PutGroupInput) -> Result<()> {
    if input.group_id.is_nil() || input.expected_version <= 0 {
        return Err(DbError::InvalidData(
            "AirHub group identity or version is invalid".to_owned(),
        ));
    }
    validate_common(&input.group, &input.active_rules, &input.actor)
}

fn validate_common(
    group: &GroupDefinition,
    rules: &[RecurrenceRuleInput],
    actor: &AirhopActor,
) -> Result<()> {
    actor.validate()?;
    let teacher_ids = group.teacher_ids.iter().copied().collect::<BTreeSet<_>>();
    let rule_ids = rules
        .iter()
        .filter_map(|rule| rule.id)
        .collect::<BTreeSet<_>>();
    if actor.kind != ActorKind::Staff
        || group.branch_id.is_nil()
        || group.room_id.is_some_and(|id| id.is_nil())
        || group.name.trim().is_empty()
        || group.name.chars().count() > 200
        || group
            .description
            .as_ref()
            .is_some_and(|value| value.chars().count() > 4_000)
        || group.min_age_months.is_some_and(|value| value < 0)
        || group.max_age_months.is_some_and(|value| value < 0)
        || matches!((group.min_age_months, group.max_age_months), (Some(min), Some(max)) if min > max)
        || group.capacity.is_some_and(|value| value <= 0)
        || group.teacher_ids.len() > MAX_TEACHERS
        || teacher_ids.len() != group.teacher_ids.len()
        || teacher_ids.contains(&Uuid::nil())
        || rules.is_empty()
        || rules.len() > MAX_RULES
        || rule_ids.len() != rules.iter().filter(|rule| rule.id.is_some()).count()
        || !valid_trial_policy(group.trial_policy_override.as_ref())
        || rules.iter().any(|rule| !valid_rule(rule))
    {
        return Err(DbError::InvalidData(
            "AirHub group input is invalid".to_owned(),
        ));
    }
    Ok(())
}

fn valid_rule(rule: &RecurrenceRuleInput) -> bool {
    let weekdays = rule.weekdays.iter().copied().collect::<BTreeSet<_>>();
    let teachers = rule
        .teacher_ids_override
        .as_ref()
        .map(|ids| ids.iter().copied().collect::<BTreeSet<_>>());
    !rule.id.is_some_and(|id| id.is_nil())
        && rule.starts_on <= rule.ends_on
        && rule.start_time < rule.end_time
        && !rule.weekdays.is_empty()
        && weekdays.len() == rule.weekdays.len()
        && !rule.branch_id_override.is_some_and(|id| id.is_nil())
        && !rule.room_id_override.is_some_and(|id| id.is_nil())
        && (rule.room_override_set || rule.room_id_override.is_none())
        && rule.capacity_override.is_none_or(|value| value > 0)
        && (rule.capacity_override_set || rule.capacity_override.is_none())
        && rule.teacher_ids_override.as_ref().is_none_or(|ids| {
            ids.len() <= MAX_TEACHERS
                && teachers
                    .as_ref()
                    .is_some_and(|unique| unique.len() == ids.len())
                && !ids.contains(&Uuid::nil())
        })
        && valid_trial_policy(rule.trial_policy_override.as_ref())
}

fn valid_trial_policy(policy: Option<&TrialPolicy>) -> bool {
    match policy {
        Some(TrialPolicy::Paid { price }) => {
            price.amount_minor <= 9_007_199_254_740_991
                && price.currency.len() == 3
                && price.currency.bytes().all(|byte| byte.is_ascii_uppercase())
        }
        _ => true,
    }
}

fn optional_json<T: Serialize>(value: Option<&T>) -> Result<Option<Value>> {
    value
        .map(serde_json::to_value)
        .transpose()
        .map_err(Into::into)
}

fn clean_optional(value: &Option<String>) -> Option<&str> {
    value
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
}

const fn weekday_str(weekday: Weekday) -> &'static str {
    match weekday {
        Weekday::Monday => "monday",
        Weekday::Tuesday => "tuesday",
        Weekday::Wednesday => "wednesday",
        Weekday::Thursday => "thursday",
        Weekday::Friday => "friday",
        Weekday::Saturday => "saturday",
        Weekday::Sunday => "sunday",
    }
}

fn parse_weekday(value: &str) -> Result<Weekday> {
    match value {
        "monday" => Ok(Weekday::Monday),
        "tuesday" => Ok(Weekday::Tuesday),
        "wednesday" => Ok(Weekday::Wednesday),
        "thursday" => Ok(Weekday::Thursday),
        "friday" => Ok(Weekday::Friday),
        "saturday" => Ok(Weekday::Saturday),
        "sunday" => Ok(Weekday::Sunday),
        other => Err(DbError::InvalidData(format!(
            "unknown AirHub recurrence weekday {other:?}"
        ))),
    }
}

#[cfg(test)]
mod tests {
    use buzz_core::CommunityId;

    use super::*;

    fn actor() -> AirhopActor {
        AirhopActor {
            kind: ActorKind::Staff,
            pubkey: Some([7; 32]),
            on_behalf_of_pubkey: None,
            agent_pubkey: None,
        }
    }

    fn group() -> GroupDefinition {
        GroupDefinition {
            branch_id: Uuid::from_u128(1),
            room_id: None,
            name: "Воздушные полотна 7–9".to_owned(),
            description: None,
            teacher_ids: Vec::new(),
            min_age_months: Some(84),
            max_age_months: Some(119),
            capacity: Some(10),
            trial_policy_override: None,
            track_attendance_override: None,
            allow_single_visits_override: None,
            status: GroupStatus::Active,
        }
    }

    fn rule() -> RecurrenceRuleInput {
        RecurrenceRuleInput {
            id: None,
            starts_on: NaiveDate::from_ymd_opt(2026, 8, 17).expect("valid test date"),
            ends_on: NaiveDate::from_ymd_opt(2026, 11, 17).expect("valid test date"),
            weekdays: vec![Weekday::Monday],
            start_time: NaiveTime::from_hms_opt(17, 0, 0).expect("valid test time"),
            end_time: NaiveTime::from_hms_opt(18, 0, 0).expect("valid test time"),
            branch_id_override: None,
            room_override_set: false,
            room_id_override: None,
            teacher_ids_override: None,
            capacity_override_set: false,
            capacity_override: None,
            trial_policy_override: None,
        }
    }

    #[test]
    fn group_validation_requires_one_valid_rule_and_unique_links() {
        let valid = CreateGroupInput {
            group: group(),
            active_rules: vec![rule()],
            idempotency_digest: [1; 32],
            request_hash: [2; 32],
            actor: actor(),
        };
        assert!(validate_create_input(&valid).is_ok());

        let mut invalid = valid.clone();
        invalid.active_rules.clear();
        assert!(validate_create_input(&invalid).is_err());

        invalid = valid;
        invalid.active_rules[0].weekdays.push(Weekday::Monday);
        assert!(validate_create_input(&invalid).is_err());
    }

    #[tokio::test]
    #[ignore = "requires a dedicated migrated Postgres database"]
    async fn group_commands_are_atomic_idempotent_and_versioned() {
        let database_url = std::env::var("BUZZ_TEST_DATABASE_URL")
            .expect("BUZZ_TEST_DATABASE_URL must point to a dedicated migrated database");
        let db = Db::new(&crate::DbConfig {
            database_url,
            max_connections: 5,
            min_connections: 0,
            ..crate::DbConfig::default()
        })
        .await
        .expect("connect test database");
        db.migrate().await.expect("migrate test database");

        let community_id = Uuid::new_v4();
        let organization_id = Uuid::new_v4();
        let branch_id = Uuid::new_v4();
        let room_id = Uuid::new_v4();
        let host = format!("group-directory-{}.test", community_id.simple());
        let tenant = TenantContext::resolved(CommunityId::from_uuid(community_id), host.clone());
        sqlx::query("INSERT INTO communities (id, host) VALUES ($1, $2)")
            .bind(community_id)
            .bind(&host)
            .execute(&db.pool)
            .await
            .expect("insert community");
        sqlx::query(
            "INSERT INTO airhop_organizations (community_id, id, name, locale, time_zone, \
                 default_trial_policy) VALUES ($1, $2, 'Group test', 'ru-RU', 'Europe/Moscow', $3)",
        )
        .bind(community_id)
        .bind(organization_id)
        .bind(json!({ "mode": "free" }))
        .execute(&db.pool)
        .await
        .expect("insert organization");
        sqlx::query(
            "INSERT INTO airhop_branches (community_id, organization_id, id, name, address) \
             VALUES ($1, $2, $3, 'Курская', 'Земляной Вал, 1')",
        )
        .bind(community_id)
        .bind(organization_id)
        .bind(branch_id)
        .execute(&db.pool)
        .await
        .expect("insert branch");
        sqlx::query(
            "INSERT INTO airhop_rooms (community_id, organization_id, id, branch_id, name) \
             VALUES ($1, $2, $3, $4, 'Большой зал')",
        )
        .bind(community_id)
        .bind(organization_id)
        .bind(room_id)
        .bind(branch_id)
        .execute(&db.pool)
        .await
        .expect("insert room");

        let mut definition = group();
        definition.branch_id = branch_id;
        definition.room_id = Some(room_id);
        let create = CreateGroupInput {
            group: definition.clone(),
            active_rules: vec![rule()],
            idempotency_digest: [1; 32],
            request_hash: [2; 32],
            actor: actor(),
        };
        let created = db
            .create_airhop_group(&tenant, &create)
            .await
            .expect("create group");
        assert_eq!(created.version, 1);
        assert!(
            db.create_airhop_group(&tenant, &create)
                .await
                .expect("replay create")
                .replayed
        );
        let groups = db.list_airhop_groups(&tenant).await.expect("list groups");
        let rules = db
            .list_airhop_recurrence_rules(&tenant)
            .await
            .expect("list recurrence rules");
        assert_eq!(groups.len(), 1);
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].weekdays, vec![Weekday::Monday]);

        definition.status = GroupStatus::Archived;
        let mut replacement = rule();
        replacement.id = Some(rules[0].id);
        replacement.end_time = NaiveTime::from_hms_opt(18, 30, 0).expect("valid test time");
        let put = PutGroupInput {
            group_id: created.group_id,
            expected_version: 1,
            group: definition,
            active_rules: vec![replacement],
            idempotency_digest: [3; 32],
            request_hash: [4; 32],
            actor: actor(),
        };
        let updated = db
            .put_airhop_group(&tenant, &put)
            .await
            .expect("update group");
        assert_eq!(updated.version, 2);
        assert_eq!(
            db.list_airhop_groups(&tenant).await.expect("reload groups")[0].status,
            GroupStatus::Archived
        );

        let mut stale = put;
        stale.idempotency_digest = [5; 32];
        stale.request_hash = [6; 32];
        assert!(matches!(
            db.put_airhop_group(&tenant, &stale).await,
            Err(DbError::AirhopVersionConflict)
        ));
    }
}
