// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as bookingDotteachersRouteImport } from "./routes/booking.teachers";
import { Route as bookingDottariffsRouteImport } from "./routes/booking.tariffs";
import { Route as bookingDotsettingsRouteImport } from "./routes/booking.settings";
import { Route as bookingDotscheduleRouteImport } from "./routes/booking.schedule";
import { Route as bookingDotrequestsRouteImport } from "./routes/booking.requests";
import { Route as bookingDotpaymentsRouteImport } from "./routes/booking.payments";
import { Route as bookingDotgroupsRouteImport } from "./routes/booking.groups";
import { Route as bookingDotdemoHostRouteImport } from "./routes/booking.demo-host";
import { Route as bookingDotclientsRouteImport } from "./routes/booking.clients";
import { Route as bookingDotbranchesRouteImport } from "./routes/booking.branches";
import { Route as bookingDotanalyticsRouteImport } from "./routes/booking.analytics";
import { Route as bookingDotpublicRouteImport } from "./routes/booking.public";
import { Route as bookingDotclientsDotindexRouteImport } from "./routes/booking.clients.index";
import { Route as bookingDotmanageDottokenRouteImport } from "./routes/booking.manage.$token";
import { Route as bookingDotclientsDotfamilyIdRouteImport } from "./routes/booking.clients.$familyId";
import { Route as channelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/channels.$channelId.posts.$postId";

const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotteachersRoute = bookingDotteachersRouteImport.update({
  id: "/booking/teachers",
  path: "/booking/teachers",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDottariffsRoute = bookingDottariffsRouteImport.update({
  id: "/booking/tariffs",
  path: "/booking/tariffs",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotsettingsRoute = bookingDotsettingsRouteImport.update({
  id: "/booking/settings",
  path: "/booking/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotscheduleRoute = bookingDotscheduleRouteImport.update({
  id: "/booking/schedule",
  path: "/booking/schedule",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotrequestsRoute = bookingDotrequestsRouteImport.update({
  id: "/booking/requests",
  path: "/booking/requests",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotpaymentsRoute = bookingDotpaymentsRouteImport.update({
  id: "/booking/payments",
  path: "/booking/payments",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotgroupsRoute = bookingDotgroupsRouteImport.update({
  id: "/booking/groups",
  path: "/booking/groups",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotdemoHostRoute = bookingDotdemoHostRouteImport.update({
  id: "/booking/demo-host",
  path: "/booking/demo-host",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotclientsRoute = bookingDotclientsRouteImport.update({
  id: "/booking/clients",
  path: "/booking/clients",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotbranchesRoute = bookingDotbranchesRouteImport.update({
  id: "/booking/branches",
  path: "/booking/branches",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotanalyticsRoute = bookingDotanalyticsRouteImport.update({
  id: "/booking/analytics",
  path: "/booking/analytics",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotpublicRoute = bookingDotpublicRouteImport.update({
  id: "/booking/",
  path: "/booking/",
  getParentRoute: () => rootRouteImport,
} as any);
const bookingDotclientsDotindexRoute =
  bookingDotclientsDotindexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => bookingDotclientsRoute,
  } as any);
const bookingDotmanageDottokenRoute =
  bookingDotmanageDottokenRouteImport.update({
    id: "/booking/manage/$token",
    path: "/booking/manage/$token",
    getParentRoute: () => rootRouteImport,
  } as any);
const bookingDotclientsDotfamilyIdRoute =
  bookingDotclientsDotfamilyIdRouteImport.update({
    id: "/$familyId",
    path: "/$familyId",
    getParentRoute: () => bookingDotclientsRoute,
  } as any);
const channelsDotchannelIdDotpostsDotpostIdRoute =
  channelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/booking/": typeof bookingDotpublicRoute;
  "/booking/analytics": typeof bookingDotanalyticsRoute;
  "/booking/branches": typeof bookingDotbranchesRoute;
  "/booking/clients": typeof bookingDotclientsRouteWithChildren;
  "/booking/demo-host": typeof bookingDotdemoHostRoute;
  "/booking/groups": typeof bookingDotgroupsRoute;
  "/booking/payments": typeof bookingDotpaymentsRoute;
  "/booking/requests": typeof bookingDotrequestsRoute;
  "/booking/schedule": typeof bookingDotscheduleRoute;
  "/booking/settings": typeof bookingDotsettingsRoute;
  "/booking/tariffs": typeof bookingDottariffsRoute;
  "/booking/teachers": typeof bookingDotteachersRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/booking/clients/$familyId": typeof bookingDotclientsDotfamilyIdRoute;
  "/booking/manage/$token": typeof bookingDotmanageDottokenRoute;
  "/booking/clients/": typeof bookingDotclientsDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/booking": typeof bookingDotpublicRoute;
  "/booking/analytics": typeof bookingDotanalyticsRoute;
  "/booking/branches": typeof bookingDotbranchesRoute;
  "/booking/demo-host": typeof bookingDotdemoHostRoute;
  "/booking/groups": typeof bookingDotgroupsRoute;
  "/booking/payments": typeof bookingDotpaymentsRoute;
  "/booking/requests": typeof bookingDotrequestsRoute;
  "/booking/schedule": typeof bookingDotscheduleRoute;
  "/booking/settings": typeof bookingDotsettingsRoute;
  "/booking/tariffs": typeof bookingDottariffsRoute;
  "/booking/teachers": typeof bookingDotteachersRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/booking/clients/$familyId": typeof bookingDotclientsDotfamilyIdRoute;
  "/booking/manage/$token": typeof bookingDotmanageDottokenRoute;
  "/booking/clients": typeof bookingDotclientsDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/booking/": typeof bookingDotpublicRoute;
  "/booking/analytics": typeof bookingDotanalyticsRoute;
  "/booking/branches": typeof bookingDotbranchesRoute;
  "/booking/clients": typeof bookingDotclientsRouteWithChildren;
  "/booking/demo-host": typeof bookingDotdemoHostRoute;
  "/booking/groups": typeof bookingDotgroupsRoute;
  "/booking/payments": typeof bookingDotpaymentsRoute;
  "/booking/requests": typeof bookingDotrequestsRoute;
  "/booking/schedule": typeof bookingDotscheduleRoute;
  "/booking/settings": typeof bookingDotsettingsRoute;
  "/booking/tariffs": typeof bookingDottariffsRoute;
  "/booking/teachers": typeof bookingDotteachersRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/booking/clients/$familyId": typeof bookingDotclientsDotfamilyIdRoute;
  "/booking/manage/$token": typeof bookingDotmanageDottokenRoute;
  "/booking/clients/": typeof bookingDotclientsDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/reminders"
    | "/settings"
    | "/booking/"
    | "/booking/analytics"
    | "/booking/branches"
    | "/booking/clients"
    | "/booking/demo-host"
    | "/booking/groups"
    | "/booking/payments"
    | "/booking/requests"
    | "/booking/schedule"
    | "/booking/settings"
    | "/booking/tariffs"
    | "/booking/teachers"
    | "/channels/$channelId"
    | "/messages/new"
    | "/booking/clients/$familyId"
    | "/booking/manage/$token"
    | "/booking/clients/"
    | "/channels/$channelId/posts/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/reminders"
    | "/settings"
    | "/booking"
    | "/booking/analytics"
    | "/booking/branches"
    | "/booking/demo-host"
    | "/booking/groups"
    | "/booking/payments"
    | "/booking/requests"
    | "/booking/schedule"
    | "/booking/settings"
    | "/booking/tariffs"
    | "/booking/teachers"
    | "/channels/$channelId"
    | "/messages/new"
    | "/booking/clients/$familyId"
    | "/booking/manage/$token"
    | "/booking/clients"
    | "/channels/$channelId/posts/$postId";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/reminders"
    | "/settings"
    | "/booking/"
    | "/booking/analytics"
    | "/booking/branches"
    | "/booking/clients"
    | "/booking/demo-host"
    | "/booking/groups"
    | "/booking/payments"
    | "/booking/requests"
    | "/booking/schedule"
    | "/booking/settings"
    | "/booking/tariffs"
    | "/booking/teachers"
    | "/channels/$channelId"
    | "/messages/new"
    | "/booking/clients/$familyId"
    | "/booking/manage/$token"
    | "/booking/clients/"
    | "/channels/$channelId/posts/$postId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  bookingDotpublicRoute: typeof bookingDotpublicRoute;
  bookingDotanalyticsRoute: typeof bookingDotanalyticsRoute;
  bookingDotbranchesRoute: typeof bookingDotbranchesRoute;
  bookingDotclientsRoute: typeof bookingDotclientsRouteWithChildren;
  bookingDotdemoHostRoute: typeof bookingDotdemoHostRoute;
  bookingDotgroupsRoute: typeof bookingDotgroupsRoute;
  bookingDotpaymentsRoute: typeof bookingDotpaymentsRoute;
  bookingDotrequestsRoute: typeof bookingDotrequestsRoute;
  bookingDotscheduleRoute: typeof bookingDotscheduleRoute;
  bookingDotsettingsRoute: typeof bookingDotsettingsRoute;
  bookingDottariffsRoute: typeof bookingDottariffsRoute;
  bookingDotteachersRoute: typeof bookingDotteachersRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  bookingDotmanageDottokenRoute: typeof bookingDotmanageDottokenRoute;
  channelsDotchannelIdDotpostsDotpostIdRoute: typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders": {
      id: "/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/teachers": {
      id: "/booking/teachers";
      path: "/booking/teachers";
      fullPath: "/booking/teachers";
      preLoaderRoute: typeof bookingDotteachersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/tariffs": {
      id: "/booking/tariffs";
      path: "/booking/tariffs";
      fullPath: "/booking/tariffs";
      preLoaderRoute: typeof bookingDottariffsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/settings": {
      id: "/booking/settings";
      path: "/booking/settings";
      fullPath: "/booking/settings";
      preLoaderRoute: typeof bookingDotsettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/schedule": {
      id: "/booking/schedule";
      path: "/booking/schedule";
      fullPath: "/booking/schedule";
      preLoaderRoute: typeof bookingDotscheduleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/requests": {
      id: "/booking/requests";
      path: "/booking/requests";
      fullPath: "/booking/requests";
      preLoaderRoute: typeof bookingDotrequestsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/payments": {
      id: "/booking/payments";
      path: "/booking/payments";
      fullPath: "/booking/payments";
      preLoaderRoute: typeof bookingDotpaymentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/groups": {
      id: "/booking/groups";
      path: "/booking/groups";
      fullPath: "/booking/groups";
      preLoaderRoute: typeof bookingDotgroupsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/demo-host": {
      id: "/booking/demo-host";
      path: "/booking/demo-host";
      fullPath: "/booking/demo-host";
      preLoaderRoute: typeof bookingDotdemoHostRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/clients": {
      id: "/booking/clients";
      path: "/booking/clients";
      fullPath: "/booking/clients";
      preLoaderRoute: typeof bookingDotclientsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/branches": {
      id: "/booking/branches";
      path: "/booking/branches";
      fullPath: "/booking/branches";
      preLoaderRoute: typeof bookingDotbranchesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/analytics": {
      id: "/booking/analytics";
      path: "/booking/analytics";
      fullPath: "/booking/analytics";
      preLoaderRoute: typeof bookingDotanalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/": {
      id: "/booking/";
      path: "/booking";
      fullPath: "/booking/";
      preLoaderRoute: typeof bookingDotpublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/clients/": {
      id: "/booking/clients/";
      path: "/";
      fullPath: "/booking/clients/";
      preLoaderRoute: typeof bookingDotclientsDotindexRouteImport;
      parentRoute: typeof bookingDotclientsRoute;
    };
    "/booking/manage/$token": {
      id: "/booking/manage/$token";
      path: "/booking/manage/$token";
      fullPath: "/booking/manage/$token";
      preLoaderRoute: typeof bookingDotmanageDottokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/booking/clients/$familyId": {
      id: "/booking/clients/$familyId";
      path: "/$familyId";
      fullPath: "/booking/clients/$familyId";
      preLoaderRoute: typeof bookingDotclientsDotfamilyIdRouteImport;
      parentRoute: typeof bookingDotclientsRoute;
    };
    "/channels/$channelId/posts/$postId": {
      id: "/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof channelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface bookingDotclientsRouteChildren {
  bookingDotclientsDotfamilyIdRoute: typeof bookingDotclientsDotfamilyIdRoute;
  bookingDotclientsDotindexRoute: typeof bookingDotclientsDotindexRoute;
}

const bookingDotclientsRouteChildren: bookingDotclientsRouteChildren = {
  bookingDotclientsDotfamilyIdRoute: bookingDotclientsDotfamilyIdRoute,
  bookingDotclientsDotindexRoute: bookingDotclientsDotindexRoute,
};

const bookingDotclientsRouteWithChildren =
  bookingDotclientsRoute._addFileChildren(bookingDotclientsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  bookingDotpublicRoute: bookingDotpublicRoute,
  bookingDotanalyticsRoute: bookingDotanalyticsRoute,
  bookingDotbranchesRoute: bookingDotbranchesRoute,
  bookingDotclientsRoute: bookingDotclientsRouteWithChildren,
  bookingDotdemoHostRoute: bookingDotdemoHostRoute,
  bookingDotgroupsRoute: bookingDotgroupsRoute,
  bookingDotpaymentsRoute: bookingDotpaymentsRoute,
  bookingDotrequestsRoute: bookingDotrequestsRoute,
  bookingDotscheduleRoute: bookingDotscheduleRoute,
  bookingDotsettingsRoute: bookingDotsettingsRoute,
  bookingDottariffsRoute: bookingDottariffsRoute,
  bookingDotteachersRoute: bookingDotteachersRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  bookingDotmanageDottokenRoute: bookingDotmanageDottokenRoute,
  channelsDotchannelIdDotpostsDotpostIdRoute:
    channelsDotchannelIdDotpostsDotpostIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
