//! Stable lesson identity and booking state transitions.

use chrono::NaiveDate;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// Stable identity of one occurrence in a recurrence series.
///
/// The original date remains stable when an exception moves the effective
/// lesson to a different date or time.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StableLessonReference {
    /// The recurrence rule that owns the occurrence.
    pub recurrence_rule_id: Uuid,
    /// The date generated by the recurrence rule before exceptions.
    pub original_date: NaiveDate,
}

/// Lifecycle status of a public or staff-created booking.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BookingStatus {
    /// The center must accept or reject the request.
    PendingConfirmation,
    /// The center accepted the request.
    Confirmed,
    /// The center rejected the request.
    Rejected,
    /// The parent cancelled the request or booking.
    CancelledByParent,
    /// The center cancelled the request or booking.
    CancelledByCenter,
}

impl BookingStatus {
    /// Returns whether this state currently reserves a place in the lesson.
    pub const fn holds_seat(self) -> bool {
        matches!(self, Self::PendingConfirmation | Self::Confirmed)
    }

    /// Returns whether the explicit transition is allowed.
    ///
    /// Repeating the same target status is idempotent and therefore allowed.
    pub const fn can_transition_to(self, target: Self) -> bool {
        if self as u8 == target as u8 {
            return true;
        }
        match self {
            Self::PendingConfirmation => matches!(
                target,
                Self::Confirmed
                    | Self::Rejected
                    | Self::CancelledByParent
                    | Self::CancelledByCenter
            ),
            Self::Confirmed => {
                matches!(target, Self::CancelledByParent | Self::CancelledByCenter)
            }
            Self::Rejected | Self::CancelledByParent | Self::CancelledByCenter => false,
        }
    }

    /// Validates a transition and returns the target status.
    pub fn transition_to(self, target: Self) -> Result<Self, BookingTransitionError> {
        if self.can_transition_to(target) {
            Ok(target)
        } else {
            Err(BookingTransitionError {
                current: self,
                target,
            })
        }
    }
}

/// A rejected booking status transition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
#[error("booking cannot transition from {current:?} to {target:?}")]
pub struct BookingTransitionError {
    /// The persisted status before the attempted command.
    pub current: BookingStatus,
    /// The status requested by the command.
    pub target: BookingStatus,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn transitions_are_explicit_and_idempotent() {
        assert!(BookingStatus::PendingConfirmation.can_transition_to(BookingStatus::Confirmed));
        assert!(BookingStatus::Confirmed.can_transition_to(BookingStatus::CancelledByParent));
        assert!(!BookingStatus::Rejected.can_transition_to(BookingStatus::Confirmed));
        assert_eq!(
            BookingStatus::Confirmed.transition_to(BookingStatus::Confirmed),
            Ok(BookingStatus::Confirmed)
        );
    }

    #[test]
    fn only_active_states_hold_a_seat() {
        assert!(BookingStatus::PendingConfirmation.holds_seat());
        assert!(BookingStatus::Confirmed.holds_seat());
        assert!(!BookingStatus::Rejected.holds_seat());
        assert!(!BookingStatus::CancelledByParent.holds_seat());
        assert!(!BookingStatus::CancelledByCenter.holds_seat());
    }
}
