//! Recurrence and exception materialization for AirHub schedules.

use std::collections::{BTreeMap, BTreeSet};

use chrono::{Datelike, NaiveDate, NaiveTime};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::age::AgeLimits;
use crate::booking::StableLessonReference;

/// A supported weekday in recurrence and enrollment rules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Weekday {
    /// Monday.
    Monday,
    /// Tuesday.
    Tuesday,
    /// Wednesday.
    Wednesday,
    /// Thursday.
    Thursday,
    /// Friday.
    Friday,
    /// Saturday.
    Saturday,
    /// Sunday.
    Sunday,
}

impl From<chrono::Weekday> for Weekday {
    fn from(value: chrono::Weekday) -> Self {
        match value {
            chrono::Weekday::Mon => Self::Monday,
            chrono::Weekday::Tue => Self::Tuesday,
            chrono::Weekday::Wed => Self::Wednesday,
            chrono::Weekday::Thu => Self::Thursday,
            chrono::Weekday::Fri => Self::Friday,
            chrono::Weekday::Sat => Self::Saturday,
            chrono::Weekday::Sun => Self::Sunday,
        }
    }
}

/// An amount represented in the currency's minor unit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Money {
    /// Non-negative amount in minor units.
    pub amount_minor: u64,
    /// ISO-4217 uppercase currency code.
    pub currency: String,
}

/// Trial availability and pricing for a group or occurrence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "mode", rename_all = "snake_case")]
pub enum TrialPolicy {
    /// Trial bookings are unavailable.
    Disabled,
    /// Trial bookings are free.
    Free,
    /// Trial bookings require the configured payment.
    Paid {
        /// Price of the trial visit.
        price: Money,
    },
}

/// Center-wide schedule policy inherited by groups and occurrences.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SchedulePolicy {
    /// Default trial policy.
    pub default_trial_policy: TrialPolicy,
    /// Whether attendance is tracked unless a group overrides it.
    pub track_attendance_by_default: bool,
    /// Whether one-off visits are allowed unless a group overrides it.
    pub allow_single_visits_by_default: bool,
}

/// Group fields required to materialize its occurrences.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GroupSchedulePolicy {
    /// Stable group identifier.
    pub id: Uuid,
    /// Default branch for the group.
    pub branch_id: Uuid,
    /// Default room, if assigned.
    pub room_id: Option<Uuid>,
    /// Default teachers.
    pub teacher_ids: Vec<Uuid>,
    /// Inclusive age limits used by booking validation.
    pub age_limits: AgeLimits,
    /// Default capacity, or unbounded when absent.
    pub capacity: Option<u32>,
    /// Group-specific trial policy.
    pub trial_policy_override: Option<TrialPolicy>,
    /// Group-specific attendance setting.
    pub track_attendance_override: Option<bool>,
    /// Group-specific one-off visit setting.
    pub allow_single_visits_override: Option<bool>,
    /// Whether the group is active in the operational schedule.
    pub active: bool,
}

/// A three-state override that distinguishes inheritance from explicit clearing.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum NullableOverride<T> {
    /// Keep the inherited value.
    #[default]
    Inherit,
    /// Explicitly remove the inherited value.
    Clear,
    /// Replace the inherited value.
    Set(T),
}

/// A recurring schedule definition.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecurrenceRule {
    /// Stable rule identifier.
    pub id: Uuid,
    /// Group that owns the series.
    pub group_id: Uuid,
    /// First possible original date, inclusive.
    pub starts_on: NaiveDate,
    /// Last possible original date, inclusive.
    pub ends_on: NaiveDate,
    /// Weekdays generated by the rule.
    pub weekdays: BTreeSet<Weekday>,
    /// Local start time.
    pub start_time: NaiveTime,
    /// Local end time.
    pub end_time: NaiveTime,
    /// Optional branch override.
    pub branch_id_override: Option<Uuid>,
    /// Room override with explicit clear support.
    pub room_id_override: NullableOverride<Uuid>,
    /// Optional teacher replacement.
    pub teacher_ids_override: Option<Vec<Uuid>>,
    /// Capacity override with explicit clear support.
    pub capacity_override: NullableOverride<u32>,
    /// Optional trial-policy replacement.
    pub trial_policy_override: Option<TrialPolicy>,
    /// Whether the rule is active in the operational schedule.
    pub active: bool,
}

impl RecurrenceRule {
    /// Returns whether the rule owns an occurrence with this original date.
    pub fn occurs_on(&self, date: NaiveDate) -> bool {
        date >= self.starts_on
            && date <= self.ends_on
            && self.weekdays.contains(&Weekday::from(date.weekday()))
    }

    fn validate(&self) -> Result<(), ScheduleError> {
        if self.starts_on > self.ends_on {
            return Err(ScheduleError::ReversedRuleRange { rule_id: self.id });
        }
        if self.start_time >= self.end_time {
            return Err(ScheduleError::InvalidRuleTime { rule_id: self.id });
        }
        if self.weekdays.is_empty() {
            return Err(ScheduleError::EmptyRuleWeekdays { rule_id: self.id });
        }
        if self
            .teacher_ids_override
            .as_ref()
            .is_some_and(|teachers| unique_count(teachers) != teachers.len())
        {
            return Err(ScheduleError::DuplicateTeachers { rule_id: self.id });
        }
        Ok(())
    }
}

/// Immutable snapshot of an occurrence before an exception was applied.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LessonOriginal {
    /// Original local start time.
    pub start_time: NaiveTime,
    /// Original local end time.
    pub end_time: NaiveTime,
    /// Original branch.
    pub branch_id: Uuid,
    /// Original room.
    pub room_id: Option<Uuid>,
    /// Original teachers.
    pub teacher_ids: Vec<Uuid>,
}

/// Partial changes applied by an override exception.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct OccurrenceOverride {
    /// Effective date replacement.
    pub date: Option<NaiveDate>,
    /// Local start-time replacement.
    pub start_time: Option<NaiveTime>,
    /// Local end-time replacement.
    pub end_time: Option<NaiveTime>,
    /// Branch replacement.
    pub branch_id: Option<Uuid>,
    /// Room replacement or explicit clear.
    pub room_id: NullableOverride<Uuid>,
    /// Teacher replacement.
    pub teacher_ids: Option<Vec<Uuid>>,
    /// Capacity replacement or explicit clear.
    pub capacity: NullableOverride<u32>,
    /// Trial-policy replacement.
    pub trial_policy: Option<TrialPolicy>,
    /// One-off visit replacement.
    pub allow_single_visits: Option<bool>,
}

/// Fully resolved effective values retained when an overridden lesson is cancelled.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OccurrenceEffective {
    /// Effective date.
    pub date: NaiveDate,
    /// Effective local start time.
    pub start_time: NaiveTime,
    /// Effective local end time.
    pub end_time: NaiveTime,
    /// Effective branch.
    pub branch_id: Uuid,
    /// Effective room.
    pub room_id: Option<Uuid>,
    /// Effective teachers.
    pub teacher_ids: Vec<Uuid>,
    /// Effective capacity.
    pub capacity: Option<u32>,
    /// Effective trial policy.
    pub trial_policy: TrialPolicy,
    /// Effective one-off visit setting.
    pub allow_single_visits: bool,
}

/// The semantic kind and payload of a lesson exception.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LessonExceptionKind {
    /// The occurrence is cancelled. `effective` preserves a prior override.
    Cancelled {
        /// Fully resolved values before cancellation, when a prior override existed.
        effective: Option<OccurrenceEffective>,
    },
    /// The occurrence remains active with partial changes.
    Override {
        /// Changes relative to the recurrence and group defaults.
        changes: OccurrenceOverride,
    },
}

/// One exception addressed by stable recurrence rule and original date.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LessonException {
    /// Stable exception identifier.
    pub id: Uuid,
    /// Recurrence rule containing the original occurrence.
    pub recurrence_rule_id: Uuid,
    /// Original recurrence date.
    pub original_date: NaiveDate,
    /// Immutable original values retained for audit and display.
    pub original: LessonOriginal,
    /// Semantic exception data.
    pub kind: LessonExceptionKind,
}

/// Materialized lifecycle of a schedule occurrence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OccurrenceStatus {
    /// No exception changed the occurrence.
    Scheduled,
    /// The effective date or time changed.
    Moved,
    /// A non-time field changed.
    Modified,
    /// The occurrence is cancelled.
    Cancelled,
}

/// A resolved occurrence used by authoritative availability and command checks.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScheduleOccurrence {
    /// Stable lesson reference.
    pub lesson_ref: StableLessonReference,
    /// Owning group.
    pub group_id: Uuid,
    /// Effective branch.
    pub branch_id: Uuid,
    /// Effective room.
    pub room_id: Option<Uuid>,
    /// Effective teachers.
    pub teacher_ids: Vec<Uuid>,
    /// Original local start time retained for display/audit.
    pub original_start_time: NaiveTime,
    /// Original local end time retained for display/audit.
    pub original_end_time: NaiveTime,
    /// Effective date.
    pub date: NaiveDate,
    /// Effective local start time.
    pub start_time: NaiveTime,
    /// Effective local end time.
    pub end_time: NaiveTime,
    /// Effective capacity, or unbounded when absent.
    pub capacity: Option<u32>,
    /// Effective trial policy.
    pub trial_policy: TrialPolicy,
    /// Whether one-off visits are allowed.
    pub single_visit_allowed: bool,
    /// Whether attendance is tracked.
    pub track_attendance: bool,
    /// Materialized status.
    pub status: OccurrenceStatus,
    /// Applied exception, if any.
    pub exception_id: Option<Uuid>,
}

/// Inclusive local-date range requested from the materializer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScheduleRange {
    /// First effective date, inclusive.
    pub starts_on: NaiveDate,
    /// Last effective date, inclusive.
    pub ends_on: NaiveDate,
}

/// Options controlling schedule materialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct MaterializeScheduleOptions {
    /// Include archived groups and recurrence rules for historical reads.
    pub include_archived: bool,
}

/// A deterministic schedule materialization failure.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum ScheduleError {
    /// The requested effective-date range is reversed.
    #[error("schedule range is reversed")]
    ReversedRange,
    /// A recurrence rule has a reversed date range.
    #[error("recurrence rule {rule_id} has a reversed date range")]
    ReversedRuleRange {
        /// Invalid rule.
        rule_id: Uuid,
    },
    /// A recurrence rule ends at or before it starts.
    #[error("recurrence rule {rule_id} has an invalid time range")]
    InvalidRuleTime {
        /// Invalid rule.
        rule_id: Uuid,
    },
    /// A recurrence rule has no weekdays.
    #[error("recurrence rule {rule_id} has no weekdays")]
    EmptyRuleWeekdays {
        /// Invalid rule.
        rule_id: Uuid,
    },
    /// A recurrence rule repeats a teacher.
    #[error("recurrence rule {rule_id} contains duplicate teachers")]
    DuplicateTeachers {
        /// Invalid rule.
        rule_id: Uuid,
    },
    /// A rule refers to a missing group.
    #[error("recurrence rule {rule_id} refers to missing group {group_id}")]
    MissingGroup {
        /// Rule with the broken reference.
        rule_id: Uuid,
        /// Missing group.
        group_id: Uuid,
    },
    /// More than one exception targets the same stable occurrence.
    #[error("multiple exceptions target recurrence rule {rule_id} on {original_date}")]
    DuplicateException {
        /// Target rule.
        rule_id: Uuid,
        /// Target original date.
        original_date: NaiveDate,
    },
    /// An exception does not address a date generated by its rule.
    #[error("exception {exception_id} targets a non-occurrence date")]
    InvalidExceptionReference {
        /// Invalid exception.
        exception_id: Uuid,
    },
    /// Final effective start/end values are invalid.
    #[error("occurrence for rule {rule_id} on {original_date} has an invalid time range")]
    InvalidEffectiveTime {
        /// Target rule.
        rule_id: Uuid,
        /// Stable original date.
        original_date: NaiveDate,
    },
    /// Iterating a date range overflowed the supported calendar.
    #[error("schedule date range overflow")]
    DateOverflow,
}

/// Materializes all occurrences whose effective date falls in `range`.
///
/// Moved exceptions are included when their original date is outside the
/// requested range but their effective date falls inside it.
pub fn materialize_schedule(
    policy: &SchedulePolicy,
    groups: &[GroupSchedulePolicy],
    rules: &[RecurrenceRule],
    exceptions: &[LessonException],
    range: ScheduleRange,
    options: MaterializeScheduleOptions,
) -> Result<Vec<ScheduleOccurrence>, ScheduleError> {
    if range.starts_on > range.ends_on {
        return Err(ScheduleError::ReversedRange);
    }

    let group_by_id: BTreeMap<Uuid, &GroupSchedulePolicy> =
        groups.iter().map(|group| (group.id, group)).collect();
    let mut exception_by_ref = BTreeMap::new();
    for exception in exceptions {
        let reference = StableLessonReference {
            recurrence_rule_id: exception.recurrence_rule_id,
            original_date: exception.original_date,
        };
        if exception_by_ref.insert(reference, exception).is_some() {
            return Err(ScheduleError::DuplicateException {
                rule_id: reference.recurrence_rule_id,
                original_date: reference.original_date,
            });
        }
    }

    let mut occurrences = BTreeMap::new();
    for rule in rules {
        rule.validate()?;
        let group =
            group_by_id
                .get(&rule.group_id)
                .copied()
                .ok_or(ScheduleError::MissingGroup {
                    rule_id: rule.id,
                    group_id: rule.group_id,
                })?;
        if !options.include_archived && (!group.active || !rule.active) {
            continue;
        }

        let first_date = rule.starts_on.max(range.starts_on);
        let last_date = rule.ends_on.min(range.ends_on);
        if first_date <= last_date {
            let mut date = first_date;
            loop {
                if rule.occurs_on(date) {
                    let reference = StableLessonReference {
                        recurrence_rule_id: rule.id,
                        original_date: date,
                    };
                    let occurrence = materialize_occurrence(
                        policy,
                        group,
                        rule,
                        date,
                        exception_by_ref.get(&reference).copied(),
                    )?;
                    occurrences.insert(reference, occurrence);
                }
                if date == last_date {
                    break;
                }
                date = date.succ_opt().ok_or(ScheduleError::DateOverflow)?;
            }
        }

        for exception in exceptions
            .iter()
            .filter(|exception| exception.recurrence_rule_id == rule.id)
        {
            if !rule.occurs_on(exception.original_date) {
                return Err(ScheduleError::InvalidExceptionReference {
                    exception_id: exception.id,
                });
            }
            if exception.original_date >= first_date && exception.original_date <= last_date {
                continue;
            }
            let Some(target_date) = exception_target_date(exception) else {
                continue;
            };
            if target_date < range.starts_on || target_date > range.ends_on {
                continue;
            }
            let reference = StableLessonReference {
                recurrence_rule_id: rule.id,
                original_date: exception.original_date,
            };
            let occurrence = materialize_occurrence(
                policy,
                group,
                rule,
                exception.original_date,
                Some(exception),
            )?;
            occurrences.insert(reference, occurrence);
        }
    }

    let mut result: Vec<_> = occurrences
        .into_values()
        .filter(|occurrence| occurrence.date >= range.starts_on && occurrence.date <= range.ends_on)
        .collect();
    result.sort_by_key(|occurrence| {
        (
            occurrence.date,
            occurrence.start_time,
            occurrence.lesson_ref,
        )
    });
    Ok(result)
}

/// Materializes one stable occurrence, or returns `None` when the rule does not own it.
pub fn materialize_schedule_occurrence(
    policy: &SchedulePolicy,
    group: &GroupSchedulePolicy,
    rule: &RecurrenceRule,
    exception: Option<&LessonException>,
    original_date: NaiveDate,
) -> Result<Option<ScheduleOccurrence>, ScheduleError> {
    rule.validate()?;
    if rule.group_id != group.id || !rule.occurs_on(original_date) {
        return Ok(None);
    }
    if exception.is_some_and(|value| {
        value.recurrence_rule_id != rule.id || value.original_date != original_date
    }) {
        return Err(ScheduleError::InvalidExceptionReference {
            exception_id: exception.map_or(Uuid::nil(), |value| value.id),
        });
    }
    materialize_occurrence(policy, group, rule, original_date, exception).map(Some)
}

fn materialize_occurrence(
    policy: &SchedulePolicy,
    group: &GroupSchedulePolicy,
    rule: &RecurrenceRule,
    original_date: NaiveDate,
    exception: Option<&LessonException>,
) -> Result<ScheduleOccurrence, ScheduleError> {
    let changes = match exception.map(|value| &value.kind) {
        Some(LessonExceptionKind::Override { changes }) => Some(changes),
        _ => None,
    };
    let effective = match exception.map(|value| &value.kind) {
        Some(LessonExceptionKind::Cancelled { effective }) => effective.as_ref(),
        _ => None,
    };

    let original_start_time = exception
        .map(|value| value.original.start_time)
        .unwrap_or(rule.start_time);
    let original_end_time = exception
        .map(|value| value.original.end_time)
        .unwrap_or(rule.end_time);
    let date = effective
        .map(|value| value.date)
        .or_else(|| changes.and_then(|value| value.date))
        .unwrap_or(original_date);
    let start_time = effective
        .map(|value| value.start_time)
        .or_else(|| changes.and_then(|value| value.start_time))
        .unwrap_or(rule.start_time);
    let end_time = effective
        .map(|value| value.end_time)
        .or_else(|| changes.and_then(|value| value.end_time))
        .unwrap_or(rule.end_time);
    if start_time >= end_time {
        return Err(ScheduleError::InvalidEffectiveTime {
            rule_id: rule.id,
            original_date,
        });
    }

    let branch_id = effective
        .map(|value| value.branch_id)
        .or_else(|| changes.and_then(|value| value.branch_id))
        .or(rule.branch_id_override)
        .unwrap_or(group.branch_id);
    let room_id = effective.map_or_else(
        || {
            resolve_nullable(
                changes.map_or(&NullableOverride::Inherit, |value| &value.room_id),
                &rule.room_id_override,
                group.room_id,
            )
        },
        |value| value.room_id,
    );
    let teacher_ids = effective
        .map(|value| value.teacher_ids.clone())
        .or_else(|| changes.and_then(|value| value.teacher_ids.clone()))
        .or_else(|| rule.teacher_ids_override.clone())
        .unwrap_or_else(|| group.teacher_ids.clone());
    let capacity = effective.map_or_else(
        || {
            resolve_nullable(
                changes.map_or(&NullableOverride::Inherit, |value| &value.capacity),
                &rule.capacity_override,
                group.capacity,
            )
        },
        |value| value.capacity,
    );
    let trial_policy = effective
        .map(|value| value.trial_policy.clone())
        .or_else(|| changes.and_then(|value| value.trial_policy.clone()))
        .or_else(|| rule.trial_policy_override.clone())
        .or_else(|| group.trial_policy_override.clone())
        .unwrap_or_else(|| policy.default_trial_policy.clone());
    let single_visit_allowed = effective
        .map(|value| value.allow_single_visits)
        .or_else(|| changes.and_then(|value| value.allow_single_visits))
        .or(group.allow_single_visits_override)
        .unwrap_or(policy.allow_single_visits_by_default);
    let moved = date != original_date || start_time != rule.start_time || end_time != rule.end_time;
    let status = match exception.map(|value| &value.kind) {
        Some(LessonExceptionKind::Cancelled { .. }) => OccurrenceStatus::Cancelled,
        Some(_) if moved => OccurrenceStatus::Moved,
        Some(_) => OccurrenceStatus::Modified,
        None => OccurrenceStatus::Scheduled,
    };

    Ok(ScheduleOccurrence {
        lesson_ref: StableLessonReference {
            recurrence_rule_id: rule.id,
            original_date,
        },
        group_id: group.id,
        branch_id,
        room_id,
        teacher_ids,
        original_start_time,
        original_end_time,
        date,
        start_time,
        end_time,
        capacity,
        trial_policy,
        single_visit_allowed,
        track_attendance: group
            .track_attendance_override
            .unwrap_or(policy.track_attendance_by_default),
        status,
        exception_id: exception.map(|value| value.id),
    })
}

fn exception_target_date(exception: &LessonException) -> Option<NaiveDate> {
    match &exception.kind {
        LessonExceptionKind::Cancelled { effective } => effective.as_ref().map(|value| value.date),
        LessonExceptionKind::Override { changes } => changes.date,
    }
}

fn resolve_nullable<T: Clone>(
    occurrence: &NullableOverride<T>,
    rule: &NullableOverride<T>,
    group: Option<T>,
) -> Option<T> {
    match occurrence {
        NullableOverride::Set(value) => Some(value.clone()),
        NullableOverride::Clear => None,
        NullableOverride::Inherit => match rule {
            NullableOverride::Set(value) => Some(value.clone()),
            NullableOverride::Clear => None,
            NullableOverride::Inherit => group,
        },
    }
}

fn unique_count<T: Ord + Copy>(values: &[T]) -> usize {
    values.iter().copied().collect::<BTreeSet<_>>().len()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn uuid(value: u128) -> Uuid {
        Uuid::from_u128(value)
    }

    fn date(value: &str) -> NaiveDate {
        NaiveDate::parse_from_str(value, "%Y-%m-%d").expect("valid test date")
    }

    fn time(value: &str) -> NaiveTime {
        NaiveTime::parse_from_str(value, "%H:%M").expect("valid test time")
    }

    fn policy() -> SchedulePolicy {
        SchedulePolicy {
            default_trial_policy: TrialPolicy::Free,
            track_attendance_by_default: true,
            allow_single_visits_by_default: false,
        }
    }

    fn group() -> GroupSchedulePolicy {
        GroupSchedulePolicy {
            id: uuid(1),
            branch_id: uuid(2),
            room_id: Some(uuid(3)),
            teacher_ids: vec![uuid(4)],
            age_limits: AgeLimits::new(Some(60), Some(84)).expect("valid limits"),
            capacity: Some(10),
            trial_policy_override: None,
            track_attendance_override: None,
            allow_single_visits_override: None,
            active: true,
        }
    }

    fn rule() -> RecurrenceRule {
        RecurrenceRule {
            id: uuid(10),
            group_id: uuid(1),
            starts_on: date("2026-08-10"),
            ends_on: date("2026-08-21"),
            weekdays: [Weekday::Tuesday, Weekday::Thursday].into_iter().collect(),
            start_time: time("10:00"),
            end_time: time("11:00"),
            branch_id_override: None,
            room_id_override: NullableOverride::Inherit,
            teacher_ids_override: None,
            capacity_override: NullableOverride::Inherit,
            trial_policy_override: None,
            active: true,
        }
    }

    fn original() -> LessonOriginal {
        LessonOriginal {
            start_time: time("10:00"),
            end_time: time("11:00"),
            branch_id: uuid(2),
            room_id: Some(uuid(3)),
            teacher_ids: vec![uuid(4)],
        }
    }

    #[test]
    fn materializes_recurrence_and_moved_exception() {
        let moved = LessonException {
            id: uuid(20),
            recurrence_rule_id: uuid(10),
            original_date: date("2026-08-13"),
            original: original(),
            kind: LessonExceptionKind::Override {
                changes: OccurrenceOverride {
                    date: Some(date("2026-08-14")),
                    start_time: Some(time("12:00")),
                    end_time: Some(time("13:00")),
                    branch_id: Some(uuid(5)),
                    room_id: NullableOverride::Clear,
                    teacher_ids: Some(vec![uuid(6)]),
                    capacity: NullableOverride::Clear,
                    trial_policy: Some(TrialPolicy::Paid {
                        price: Money {
                            amount_minor: 90_000,
                            currency: "RUB".to_owned(),
                        },
                    }),
                    allow_single_visits: Some(true),
                },
            },
        };

        let occurrences = materialize_schedule(
            &policy(),
            &[group()],
            &[rule()],
            &[moved],
            ScheduleRange {
                starts_on: date("2026-08-10"),
                ends_on: date("2026-08-21"),
            },
            MaterializeScheduleOptions::default(),
        )
        .expect("materialize");

        assert_eq!(occurrences.len(), 4);
        let changed = occurrences
            .iter()
            .find(|value| value.lesson_ref.original_date == date("2026-08-13"))
            .expect("moved occurrence");
        assert_eq!(changed.date, date("2026-08-14"));
        assert_eq!(changed.status, OccurrenceStatus::Moved);
        assert_eq!(changed.branch_id, uuid(5));
        assert_eq!(changed.room_id, None);
        assert_eq!(changed.capacity, None);
        assert!(changed.single_visit_allowed);
    }

    #[test]
    fn moved_exception_enters_effective_range_by_stable_reference() {
        let moved = LessonException {
            id: uuid(20),
            recurrence_rule_id: uuid(10),
            original_date: date("2026-08-11"),
            original: original(),
            kind: LessonExceptionKind::Override {
                changes: OccurrenceOverride {
                    date: Some(date("2026-08-20")),
                    ..OccurrenceOverride::default()
                },
            },
        };
        let occurrences = materialize_schedule(
            &policy(),
            &[group()],
            &[rule()],
            &[moved],
            ScheduleRange {
                starts_on: date("2026-08-20"),
                ends_on: date("2026-08-20"),
            },
            MaterializeScheduleOptions::default(),
        )
        .expect("materialize");

        assert_eq!(occurrences.len(), 2);
        assert!(occurrences.iter().any(|value| {
            value.lesson_ref.original_date == date("2026-08-11") && value.date == date("2026-08-20")
        }));
    }

    #[test]
    fn cancellation_preserves_effective_override_values() {
        let cancelled = LessonException {
            id: uuid(20),
            recurrence_rule_id: uuid(10),
            original_date: date("2026-08-11"),
            original: original(),
            kind: LessonExceptionKind::Cancelled {
                effective: Some(OccurrenceEffective {
                    date: date("2026-08-12"),
                    start_time: time("12:00"),
                    end_time: time("13:00"),
                    branch_id: uuid(5),
                    room_id: None,
                    teacher_ids: vec![uuid(6)],
                    capacity: None,
                    trial_policy: TrialPolicy::Free,
                    allow_single_visits: true,
                }),
            },
        };
        let occurrence = materialize_schedule_occurrence(
            &policy(),
            &group(),
            &rule(),
            Some(&cancelled),
            date("2026-08-11"),
        )
        .expect("materialize")
        .expect("occurrence");

        assert_eq!(occurrence.status, OccurrenceStatus::Cancelled);
        assert_eq!(occurrence.date, date("2026-08-12"));
        assert!(occurrence.single_visit_allowed);
    }
}
